version: '3.6'

volumes:
  database_data:
    driver: local

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamesdb
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
  app:
    build: .
    command: ["sql-migrate", "up", "-env", "test"]
    restart: always
    ports:
      - 10045:10045
    depends_on:
      - postgresdb



